-- Create the store_settings table
CREATE TABLE IF NOT EXISTS public.store_settings (
    id bigint generated by default as identity primary key,
    store_name text,
    support_email text,
    currency text,
    timezone text,
    payment_gateways jsonb default '{"stripe": true, "paypal": false}'::jsonb,
    shipping_methods jsonb default '[]'::jsonb,
    show_decimals boolean default false,
    smtp_host text,
    smtp_port integer default 587,
    smtp_user text,
    smtp_pass text,
    smtp_from text,
    smtp_secure boolean default true,
    email_notifications_enabled boolean default false,
    logo_url text,
    hero_image_url text,
    tax_rates jsonb default '{"enabled": true, "rates": [], "taxConfig": {"enabled": true, "name": "Tax", "type": "percentage", "value": 0, "showInCheckout": true}}'::jsonb,
    privacy_policy text,
    terms_of_service text,
    returns_policy text,
    size_guide text,
    contact_phone text,
    contact_address text,
    operating_hours jsonb,
    instagram_url text,
    twitter_url text,
    facebook_url text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
ALTER TABLE public.store_settings ENABLE ROW LEVEL SECURITY;

-- Create policy to allow all authenticated users to read/update
-- Adjust this in production to restrict updates to admins only
CREATE POLICY "Enable all access for authenticated users" ON public.store_settings
FOR ALL USING (auth.role() = 'authenticated');

-- Insert default settings if not exists
INSERT INTO public.store_settings (id, store_name, support_email, currency, timezone, payment_gateways, shipping_methods)
VALUES (
    1,
    'Nakma Fitness',
    'support@nakmastore.com',
    'USD',
    'EST',
    '{"stripe": true, "paypal": false}'::jsonb,
    '{"standard": true, "express": true, "free": true}'::jsonb
)
ON CONFLICT (id) DO NOTHING;
