-- NAKMA Store - Master Setup Script
-- Consolidated Schema Migration
-- Generated: 2026-01-10
-- V3: Updated to be fully idempotent with schema evolution (adds missing columns)

BEGIN;

--------------------------------------------------------------------------------
-- 1. Base Helpers & Utilities
--------------------------------------------------------------------------------

-- Enable UUID extension if not exists
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Function to update 'updated_at' timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

--------------------------------------------------------------------------------
-- 2. Store Settings
--------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.store_settings (
    id bigint generated by default as identity primary key,
    store_name text,
    support_email text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Schema Evolution: Add columns if they don't exist
DO $$
BEGIN
    ALTER TABLE public.store_settings ADD COLUMN IF NOT EXISTS logo_url text;
    ALTER TABLE public.store_settings ADD COLUMN IF NOT EXISTS hero_image_url text;
    ALTER TABLE public.store_settings ADD COLUMN IF NOT EXISTS currency text DEFAULT 'USD';
    ALTER TABLE public.store_settings ADD COLUMN IF NOT EXISTS timezone text DEFAULT 'UTC';
    ALTER TABLE public.store_settings ADD COLUMN IF NOT EXISTS show_decimals boolean default false;
    ALTER TABLE public.store_settings ADD COLUMN IF NOT EXISTS privacy_policy text;
    ALTER TABLE public.store_settings ADD COLUMN IF NOT EXISTS terms_of_service text;
    ALTER TABLE public.store_settings ADD COLUMN IF NOT EXISTS returns_policy text;
    ALTER TABLE public.store_settings ADD COLUMN IF NOT EXISTS size_guide text;
    ALTER TABLE public.store_settings ADD COLUMN IF NOT EXISTS contact_phone text;
    ALTER TABLE public.store_settings ADD COLUMN IF NOT EXISTS contact_address text;
    ALTER TABLE public.store_settings ADD COLUMN IF NOT EXISTS operating_hours jsonb;
    ALTER TABLE public.store_settings ADD COLUMN IF NOT EXISTS payment_gateways jsonb default '{"stripe": true, "paypal": false, "paystack": true, "cod": true}'::jsonb;
    ALTER TABLE public.store_settings ADD COLUMN IF NOT EXISTS shipping_methods jsonb default '[]'::jsonb;
    ALTER TABLE public.store_settings ADD COLUMN IF NOT EXISTS tax_rates jsonb default '{"enabled": true, "rates": [], "taxConfig": {"enabled": true, "name": "Tax", "type": "percentage", "value": 0, "showInCheckout": true}}'::jsonb;
    ALTER TABLE public.store_settings ADD COLUMN IF NOT EXISTS smtp_host text;
    ALTER TABLE public.store_settings ADD COLUMN IF NOT EXISTS smtp_port integer default 587;
    ALTER TABLE public.store_settings ADD COLUMN IF NOT EXISTS smtp_user text;
    ALTER TABLE public.store_settings ADD COLUMN IF NOT EXISTS smtp_pass text;
    ALTER TABLE public.store_settings ADD COLUMN IF NOT EXISTS smtp_from text;
    ALTER TABLE public.store_settings ADD COLUMN IF NOT EXISTS smtp_secure boolean default true;
    ALTER TABLE public.store_settings ADD COLUMN IF NOT EXISTS email_notifications_enabled boolean default false;
    ALTER TABLE public.store_settings ADD COLUMN IF NOT EXISTS resend_config jsonb;
    ALTER TABLE public.store_settings ADD COLUMN IF NOT EXISTS instagram_url text;
    ALTER TABLE public.store_settings ADD COLUMN IF NOT EXISTS twitter_url text;
    ALTER TABLE public.store_settings ADD COLUMN IF NOT EXISTS facebook_url text;
    ALTER TABLE public.store_settings ADD COLUMN IF NOT EXISTS homepage_settings jsonb default '{
        "hero": { "title": "Store Name", "subtitle": "Welcome", "imageUrl": "" },
        "featured": { "title": "Featured", "products": [] }
    }'::jsonb;
    ALTER TABLE public.store_settings ADD COLUMN IF NOT EXISTS navigation_settings jsonb default '[]'::jsonb;
    ALTER TABLE public.store_settings ADD COLUMN IF NOT EXISTS about_page_settings jsonb;
    ALTER TABLE public.store_settings ADD COLUMN IF NOT EXISTS login_page_settings jsonb;
    ALTER TABLE public.store_settings ADD COLUMN IF NOT EXISTS checkout_page_settings jsonb;
    ALTER TABLE public.store_settings ADD COLUMN IF NOT EXISTS site_url text;
    ALTER TABLE public.store_settings ADD COLUMN IF NOT EXISTS alert_emails text[];
    ALTER TABLE public.store_settings ADD COLUMN IF NOT EXISTS seo_settings jsonb;
    ALTER TABLE public.store_settings ADD COLUMN IF NOT EXISTS brand_settings jsonb DEFAULT '{
        "primaryColor": "#b82063",
        "secondaryColor": "#000000",
        "accentColor": "#d86928",
        "backgroundColor": "#000000"
    }'::jsonb;
END $$;

-- Enable RLS
ALTER TABLE public.store_settings ENABLE ROW LEVEL SECURITY;

-- Drop policy if exists to avoid errors on re-run
DROP POLICY IF EXISTS "Enable all access for authenticated users" ON public.store_settings;

-- Allow authenticated users to read/update
CREATE POLICY "Enable all access for authenticated users" ON public.store_settings
FOR ALL USING (auth.role() = 'authenticated');

-- Insert default settings
INSERT INTO public.store_settings (id, store_name, support_email, currency)
VALUES (1, 'NAKMA Store', 'info@nakmaltd.com', 'USD')
ON CONFLICT (id) DO UPDATE SET
    store_name = EXCLUDED.store_name,
    support_email = EXCLUDED.support_email;


--------------------------------------------------------------------------------
-- 3. Team Handling & Profiles
--------------------------------------------------------------------------------

-- Profiles table (extends auth.users)
CREATE TABLE IF NOT EXISTS profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id)
);

DO $$
BEGIN
    ALTER TABLE profiles ADD COLUMN IF NOT EXISTS email TEXT;
    ALTER TABLE profiles ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'customer';
    ALTER TABLE profiles ADD COLUMN IF NOT EXISTS full_name TEXT;
    ALTER TABLE profiles ADD COLUMN IF NOT EXISTS avatar_url TEXT;
    ALTER TABLE profiles ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
    ALTER TABLE profiles ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
END $$;

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public profiles are viewable by everyone" ON profiles;
DROP POLICY IF EXISTS "Users can insert their own profile" ON profiles;
DROP POLICY IF EXISTS "Users can update own profile" ON profiles;

CREATE POLICY "Public profiles are viewable by everyone" ON profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile" ON profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE USING (auth.uid() = id);

-- Team Members
CREATE TABLE IF NOT EXISTS team_members (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email TEXT UNIQUE NOT NULL
);

DO $$
BEGIN
    ALTER TABLE team_members ADD COLUMN IF NOT EXISTS full_name TEXT;
    ALTER TABLE team_members ADD COLUMN IF NOT EXISTS role TEXT NOT NULL DEFAULT 'viewer' CHECK (role IN ('admin', 'editor', 'shop_manager', 'viewer'));
    ALTER TABLE team_members ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'pending'));
    ALTER TABLE team_members ADD COLUMN IF NOT EXISTS invited_by UUID REFERENCES auth.users(id);
    ALTER TABLE team_members ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
    ALTER TABLE team_members ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
END $$;

ALTER TABLE team_members ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow authenticated users to read team members" ON team_members;
DROP POLICY IF EXISTS "Allow admins to manage team members" ON team_members;

CREATE POLICY "Allow authenticated users to read team members"
    ON team_members FOR SELECT TO authenticated USING (true);

CREATE POLICY "Allow admins to manage team members"
    ON team_members FOR ALL TO authenticated
    USING (
        EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
        OR
        EXISTS (SELECT 1 FROM team_members WHERE email = auth.jwt()->>'email' AND role = 'admin')
    );

--------------------------------------------------------------------------------
-- 4. Product, Variations Order Management
--------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS products (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    price DECIMAL(10,2) NOT NULL
);

DO $$
BEGIN
    ALTER TABLE products ADD COLUMN IF NOT EXISTS description TEXT;
    ALTER TABLE products ADD COLUMN IF NOT EXISTS sale_price DECIMAL(10,2);
    ALTER TABLE products ADD COLUMN IF NOT EXISTS images TEXT[];
    ALTER TABLE products ADD COLUMN IF NOT EXISTS category TEXT;
    ALTER TABLE products ADD COLUMN IF NOT EXISTS stock INTEGER DEFAULT 0;
    ALTER TABLE products ADD COLUMN IF NOT EXISTS sku TEXT;
    ALTER TABLE products ADD COLUMN IF NOT EXISTS is_featured BOOLEAN DEFAULT false;
    ALTER TABLE products ADD COLUMN IF NOT EXISTS is_archived BOOLEAN DEFAULT false;
    ALTER TABLE products ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
    ALTER TABLE products ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
END $$;

ALTER TABLE products ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public read products" ON products;
DROP POLICY IF EXISTS "Admins manage products" ON products;

CREATE POLICY "Public read products" ON products FOR SELECT USING (true);
CREATE POLICY "Admins manage products" ON products FOR ALL USING (auth.role() = 'authenticated');


CREATE TABLE IF NOT EXISTS product_variations (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    product_id UUID REFERENCES products(id) ON DELETE CASCADE,
    name TEXT NOT NULL
);

DO $$
BEGIN
    ALTER TABLE product_variations ADD COLUMN IF NOT EXISTS sku TEXT;
    ALTER TABLE product_variations ADD COLUMN IF NOT EXISTS price DECIMAL(10,2);
    ALTER TABLE product_variations ADD COLUMN IF NOT EXISTS stock INTEGER DEFAULT 0;
    ALTER TABLE product_variations ADD COLUMN IF NOT EXISTS options JSONB;
    ALTER TABLE product_variations ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
END $$;

CREATE INDEX IF NOT EXISTS idx_product_variations_product_id ON product_variations(product_id);

CREATE TABLE IF NOT EXISTS admin_notifications (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    type TEXT NOT NULL,
    title TEXT NOT NULL,
    message TEXT NOT NULL
);

DO $$
BEGIN
    ALTER TABLE admin_notifications ADD COLUMN IF NOT EXISTS is_read BOOLEAN DEFAULT FALSE;
    ALTER TABLE admin_notifications ADD COLUMN IF NOT EXISTS link TEXT;
    ALTER TABLE admin_notifications ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
END $$;

CREATE TABLE IF NOT EXISTS orders (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    total_amount DECIMAL(10,2) NOT NULL
);

DO $$
BEGIN
    ALTER TABLE orders ADD COLUMN IF NOT EXISTS customer_id UUID REFERENCES auth.users(id);
    ALTER TABLE orders ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'Pending';
    ALTER TABLE orders ADD COLUMN IF NOT EXISTS shipping_address JSONB;
    ALTER TABLE orders ADD COLUMN IF NOT EXISTS billing_address JSONB;
    ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_method TEXT;
    ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_status TEXT DEFAULT 'Pending';
    ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_reference TEXT;
    ALTER TABLE orders ADD COLUMN IF NOT EXISTS tracking_number TEXT;
    ALTER TABLE orders ADD COLUMN IF NOT EXISTS notes TEXT;
    ALTER TABLE orders ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
    ALTER TABLE orders ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
END $$;

ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS order_items (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    order_id UUID REFERENCES orders(id) ON DELETE CASCADE,
    product_id UUID REFERENCES products(id),
    quantity INTEGER NOT NULL,
    price DECIMAL(10,2) NOT NULL
);

DO $$
BEGIN
    ALTER TABLE order_items ADD COLUMN IF NOT EXISTS variation_id UUID REFERENCES product_variations(id) ON DELETE SET NULL;
    ALTER TABLE order_items ADD COLUMN IF NOT EXISTS variation_name TEXT;
    ALTER TABLE order_items ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
END $$;

ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;

-- Order Policies
DROP POLICY IF EXISTS "Users view own orders" ON orders;
DROP POLICY IF EXISTS "Admins view all orders" ON orders;
DROP POLICY IF EXISTS "Admins manage orders" ON orders;
DROP POLICY IF EXISTS "Admins delete orders" ON orders;
DROP POLICY IF EXISTS "Public create orders" ON orders;

CREATE POLICY "Users view own orders" ON orders FOR SELECT USING (auth.uid() = customer_id);
CREATE POLICY "Admins view all orders" ON orders FOR SELECT USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);
CREATE POLICY "Admins manage orders" ON orders FOR UPDATE USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);
CREATE POLICY "Admins delete orders" ON orders FOR DELETE USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);
CREATE POLICY "Public create orders" ON orders FOR INSERT WITH CHECK (true);

-- Order Items Policies
DROP POLICY IF EXISTS "Users view own order items" ON order_items;
DROP POLICY IF EXISTS "Admins view all order items" ON order_items;
DROP POLICY IF EXISTS "Public create order items" ON order_items;

CREATE POLICY "Users view own order items" ON order_items FOR SELECT USING (
    EXISTS (SELECT 1 FROM orders WHERE orders.id = order_items.order_id AND orders.customer_id = auth.uid())
);
CREATE POLICY "Admins view all order items" ON order_items FOR SELECT USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);
CREATE POLICY "Public create order items" ON order_items FOR INSERT WITH CHECK (true);


--------------------------------------------------------------------------------
-- 5. Content Management (Articles & Pages)
--------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS article_categories (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL UNIQUE
);

DO $$
BEGIN
    ALTER TABLE article_categories ADD COLUMN IF NOT EXISTS slug TEXT;
    -- If slug was just added, it might be null, but we want it unique/not null in future. 
    -- For now, loose check.
    ALTER TABLE article_categories ADD COLUMN IF NOT EXISTS description TEXT;
    ALTER TABLE article_categories ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
END $$;

CREATE TABLE IF NOT EXISTS articles (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    title TEXT NOT NULL
);

DO $$
BEGIN
    ALTER TABLE articles ADD COLUMN IF NOT EXISTS slug TEXT;
    ALTER TABLE articles ADD COLUMN IF NOT EXISTS excerpt TEXT;
    ALTER TABLE articles ADD COLUMN IF NOT EXISTS content TEXT;
    ALTER TABLE articles ADD COLUMN IF NOT EXISTS featured_image TEXT;
    ALTER TABLE articles ADD COLUMN IF NOT EXISTS author_id UUID REFERENCES auth.users(id);
    ALTER TABLE articles ADD COLUMN IF NOT EXISTS category_id UUID REFERENCES article_categories(id);
    ALTER TABLE articles ADD COLUMN IF NOT EXISTS is_published BOOLEAN DEFAULT FALSE;
    ALTER TABLE articles ADD COLUMN IF NOT EXISTS published_at TIMESTAMP WITH TIME ZONE;
    ALTER TABLE articles ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
    ALTER TABLE articles ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
END $$;

ALTER TABLE articles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public view published articles" ON articles;
DROP POLICY IF EXISTS "Admins manage articles" ON articles;

CREATE POLICY "Public view published articles" ON articles FOR SELECT USING (is_published = true);
CREATE POLICY "Admins manage articles" ON articles FOR ALL USING (auth.role() = 'authenticated');


CREATE TABLE IF NOT EXISTS pages (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    title TEXT NOT NULL
);

DO $$
BEGIN
    ALTER TABLE pages ADD COLUMN IF NOT EXISTS slug TEXT;
    ALTER TABLE pages ADD COLUMN IF NOT EXISTS content TEXT;
    ALTER TABLE pages ADD COLUMN IF NOT EXISTS is_published BOOLEAN DEFAULT FALSE;
    ALTER TABLE pages ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'published';
    ALTER TABLE pages ADD COLUMN IF NOT EXISTS custom_css TEXT;
    ALTER TABLE pages ADD COLUMN IF NOT EXISTS meta_title TEXT;
    ALTER TABLE pages ADD COLUMN IF NOT EXISTS meta_description TEXT;
    ALTER TABLE pages ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
    ALTER TABLE pages ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
END $$;

ALTER TABLE pages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public view published pages" ON pages;
DROP POLICY IF EXISTS "Admins manage pages" ON pages;

CREATE POLICY "Public view published pages" ON pages FOR SELECT USING (is_published = true);
CREATE POLICY "Admins manage pages" ON pages FOR ALL USING (auth.role() = 'authenticated');

--------------------------------------------------------------------------------
-- 6. Analytics
--------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS analytics_events (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    event_type TEXT NOT NULL
);

-- Analytics Missing Columns
DO $$
BEGIN
    ALTER TABLE analytics_events ADD COLUMN IF NOT EXISTS persistent_id TEXT;
    ALTER TABLE analytics_events ADD COLUMN IF NOT EXISTS event_name TEXT;
    ALTER TABLE analytics_events ADD COLUMN IF NOT EXISTS page_url TEXT;
    ALTER TABLE analytics_events ADD COLUMN IF NOT EXISTS referrer TEXT;
    ALTER TABLE analytics_events ADD COLUMN IF NOT EXISTS user_agent TEXT;
    ALTER TABLE analytics_events ADD COLUMN IF NOT EXISTS page_path TEXT;
    ALTER TABLE analytics_events ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id);
    ALTER TABLE analytics_events ADD COLUMN IF NOT EXISTS session_id TEXT;
    ALTER TABLE analytics_events ADD COLUMN IF NOT EXISTS metadata JSONB;
    ALTER TABLE analytics_events ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
END $$;

ALTER TABLE analytics_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins view analytics" ON analytics_events;
DROP POLICY IF EXISTS "Public log events" ON analytics_events;

CREATE POLICY "Admins view analytics" ON analytics_events FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Public log events" ON analytics_events FOR INSERT WITH CHECK (true); 

-- Orders Missing Columns
DO $$
BEGIN
    ALTER TABLE orders ADD COLUMN IF NOT EXISTS is_viewed BOOLEAN DEFAULT FALSE;
END $$; 

--------------------------------------------------------------------------------
-- 7. Triggers & Functions
--------------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION decrement_product_stock(prod_id UUID, qty INTEGER)
RETURNS VOID AS $$
BEGIN
    UPDATE products SET stock = GREATEST(0, stock - qty) WHERE id = prod_id;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION decrement_variation_stock(var_id UUID, qty INTEGER)
RETURNS VOID AS $$
BEGIN
    UPDATE product_variations SET stock = GREATEST(0, stock - qty) WHERE id = var_id;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION handle_low_stock_notification()
RETURNS TRIGGER AS $$
BEGIN
    IF (NEW.stock <= 5 AND (OLD.stock IS NULL OR OLD.stock > 5)) THEN
        INSERT INTO admin_notifications (type, title, message, link)
        VALUES (
            'low_stock',
            'Low Stock Alert: ' || (SELECT name FROM products WHERE id = NEW.product_id),
            'Variation "' || NEW.name || '" is low on stock: ' || NEW.stock,
            '/admin/products'
        );
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tr_variation_low_stock ON product_variations;
CREATE TRIGGER tr_variation_low_stock
    AFTER UPDATE OF stock ON product_variations
    FOR EACH ROW
    EXECUTE FUNCTION handle_low_stock_notification();

-- Final Commit
COMMIT;
